### Get main page
GET https://cse341-project1-nld0.onrender.com

### Get all contacts
GET https://cse341-project1-nld0.onrender.com/contacts

### Get single contact
GET https://cse341-project1-nld0.onrender.com/contacts/69ab257b1dfc051d8f4a40da

### Create contact
POST https://cse341-project1-nld0.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Colleen",
    "lastName": "Quiner",
    "email": "momq@fakeemail.com",
    "favoriteColor": "blue",
    "birthDate": "2041-09-17"
}

### Update contact
PUT https://cse341-project1-nld0.onrender.com/contacts/69b3ff50e7405f20b918f9a1
Content-Type: application/json

{
    "firstName": "Colleen",
    "lastName": "Quiner",
    "email": "momq@fakeemail.com",
    "favoriteColor": "blue",
    "birthDate": "2041-09-17"
}

### Delete contact
DELETE https://cse341-project1-nld0.onrender.com/contacts/69ab257b1dfc051d8f4a40da


